#!/bin/bash 
# 
# Copyright (c) 2024 Danila Skachedubov <skachedubovda@altlinux.org> 
# 
# Example diagnostic tool 
# 
# SPDX-License-Identifier: GPL-2.0-or-later 
#

set -euo pipefail

PROG_VERSION='0.0.1'
PROG="${0##*/}"

print_version()
{
	cat <<EOF
$PROG version $PROG_VERSION
EOF
	exit
}

show_usage() {
    cat << EOF
Usage: $0 [options]

Options:
  -l, --list        print the list of domain validation checks
  -V, --version     print program version and exit
  -h, --help        show this help message

EOF
  exit
}

TEMP=$(getopt -n "$PROG" -o "l,V,h" -l "list,version,help" -- "$@") || show_usage
eval set -- "$TEMP"

log_message() {
    local log_level="$1"
    local message="$2"
    echo "[$log_level] $message"
}

print_checks() {
    cat << EOF
Domain validation checks:
1. View general information about the domain.
2.
3. 
4.
EOF
    exit
}

check_domain_info() {
    local domain_ip="127.0.0.1"
    log_message "INFO" "Checking domain information for IP: $domain_ip"

    if command -v samba-tool &> /dev/null; then
        samba-tool domain info "$domain_ip"
        log_message "INFO" "Domain information check completed successfully."
    else
        log_message "ERROR" "samba-tool command not found."
        exit 1
    fi
}

while true; do
    case "$1" in
        -l|--list) print_checks; shift ;;
        -V|--version) print_version shift ;;
        -h|--help) show_usage; shift ;;
        --) shift; break ;;
        *) show_usage ;;
    esac
done

log_message "INFO" "Diagnostic tool started"
check_domain_info

# TODO: Добавить проверки:
# Предоставляемых служб(smbclient -L localhost -Uadministrator)
# Наличия nameserver 127.0.0.1 в /etc/resolv.conf: 
# Имён хостов: адрес _kerberos._udp.*адрес домена с точкой
#              адрес _ldap._tcp.*адрес домена с точкой:
#              адрес хоста.*адрес домена с точкой:
# Проверка Kerberos